version: '3.8'
services:
  notes_db:
    image: "postgres:17.2"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    volumes:
      - notes-data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis-cache:
    image: 'redis:7.4.2'
    ports:
      - "6379:6379"
volumes:
  notes-data:
